### ISSUE TITLE
Thoughts on encoding XML entities

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#103]
Expanding my test cases ...

One of the products I found has a name like `Bestellerweiterung für E&F Umbau`. This confuses the XML parser when I'm attaching the ZUGFeRD file to the PDF:
```
org.dom4j.DocumentException: Error on line 26 of document  : Referenz zu Entity "F" muss mit dem Begrenzungszeichen ";" enden.
	at org.dom4j.io.SAXReader.read(SAXReader.java:462)
	at org.dom4j.DocumentHelper.parseText(DocumentHelper.java:286)
	at org.mustangproject.ZUGFeRD.ZUGFeRD2PullProvider.getXML(ZUGFeRD2PullProvider.java:143)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporter.PDFattachZugferdFile(ZUGFeRDExporter.java:375)
```

Is the user responsible for encoding the basic XML entities `<`, `>`, `&`, `"` and `'` in the input? If so, the documentation should say so more loudly.

If we forced encoding in the ZUGFeRD*PullProvider, it would break the code of users who already encoded the strings in their code.

In the interest of streamlining the user experience : How about providing a helper [like this one](https://stackoverflow.com/a/48588062) as, say, `ZUGFeRDExporter.encode(string)`, and introducing it in the example on the website with a company name like "Eine GmbH & Co. KG"? That would be in step 14 in "Write a ZUGFeRD-PDF file".

**Comment by jstaerk** [comment]
no, that's a bug. I thought I had added a unit test with < but somehow that seemed to work. I added a unit test ZF2EdgeTest for this kind of cases but it does not yet fail, I guess it's soon time to merge ZUV (and integrate in the unit tests). The helper looks reasonable but it should automatically be called internally on all strings.

Despite this is clearly my fault because I still refuse to switch to JAXB for ZF2 (#87) despite it is already used for ZF1 (these kind of issues do not happen there):  I do still consider JAXB a big overhead.
