### ISSUE TITLE
Implemented dependencies in Mustang

### ISSUE THREAD

**Issue by Novaax** [ZUGFeRD/mustangproject#138]
Hello,

we have a problem with the implemented Saxon-HE version in your JAR file.

The problem is actually that we are using xml-Beans in our program and the library needs a lower version of SAXON to work normally. 

Our question is now:
Will there be a version where you don't import all the required jar files into the Mustang JAR?

Kind regards,

Novaax

**Comment by jstaerk** [comment]
I believe in 1.7.x it is only used for the miration from zf1 to zf2, which I want to get rid off, because it's experimental, dangerous and apparently not "carried" by the community. But as of 1.8 saxon will also be required for the visualization (i.e. conversion from xml to XHTML). And later on https://github.com/ZUGFeRD/ZUV/ will be integrated which needs Saxon for schematron checks (carried out via XSLT). So currently you could only download the plain jar without *any* depencencies as documented on https://mustangproject.org/use/#JAR and hope your Saxon version supports what Mustang needs...
