### ISSUE TITLE
The pom in the release differs from the one in the mvn-repo branch

### ISSUE THREAD

**Issue by JannickWeisshaupt** [ZUGFeRD/mustangproject#143]
## Expected behaviour
The jar under release contains a correct pom, which can be readily used. The pom under 
https://github.com/ZUGFeRD/mustangproject/tree/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.7.5 and releases are the same.
## Actual behaviour
The pom in the release jar differs from the one under https://github.com/ZUGFeRD/mustangproject/tree/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.7.5. It includes external references such as org.sanityinc.jargs, which can in my case not be resolved.

**Comment by jstaerk** [comment]
Hi,
very interesting observation but I suggest your expected behaviour might be wrong: you compare two different branches, the master branch which is used to build the software vis á vis the mvn-repo branch which is used to *deliver* (the compiled assembled binary Jar of) the software via maven.

If you want to *build* Mustang itself, Jargs has the issue that it is only available as snapshot, at least it is still availble on my computer but maven notoriously caches downloads. `mvn clean package` should build disregarding the snapshot but if if you experience issues maybe the 
[developer documentation](https://github.com/ZUGFeRD/mustangproject/blob/master/doc/development_documentation.md#release) could help, e.g. with some maven commands you might require `-DignoreSnapshots=true`

kind regards
Jochen
