### ISSUE TITLE
re-enable javadoc

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#24]
it's currently disabled because it throws errors which should be corrected

**Comment by jstaerk** [comment]
mvn javadoc:javadoc does something, as soon as I find out where to get the files from I can put it on the hp and close this

**Comment by swsch** [comment]
I see lots of lines like 
```
mustangproject\target\site\apidocs\org\mustangproject\ZUGFeRD\model\class-use\PercentType.html
```
so you'll probably have to flip the backslashes around. `target/site/apidocs` seems the place to go.

I wonder if there's a way to restrict javadoc to only look at the project sources and hence avoid the ton of warnings caused by lacking javadoc comments under `target/generated-sources`.

**Comment by jstaerk** [comment]
i did not yet check the forward slashes (pls let me know if that's still an issue) but the javadocs are now published separately
