### ISSUE TITLE
New Feature request: Command line parameter to disable the filelog output

### ISSUE THREAD

**Issue by chaaseSimova** [ZUGFeRD/mustangproject#259]
Hi Jochen, 
can you add a switch as a command line parameter to disable the filelog output?

Thank you in advanced. I wish you nice days before x-mas and a wonderful feat to you, your team and your family. 
Best regards,

Christian

**Comment by jstaerk** [comment]
I already tried two times but I might try a third time. It also bugs me but the logging is configured in a xml file and interestingly so far I was unable to figure out how to precisely (migrate that to code or) programmatically override that.

**Comment by jstaerk** [comment]
see also #215

**Comment by martinariehm** [comment]
See [here](https://logback.qos.ch/manual/configuration.html) for how to configure logback. One common way is to have a fallback logback.xml in the classpath (not in the library but, in the program that uses the library) but have the program first look in the file system for a file. This can then be changed so that logging into file will not happen for calls in the library.

**Comment by jstaerk** [comment]
sorry no success so far
