### ISSUE TITLE
How to disable the ZUV log file

### ISSUE THREAD

**Issue by kassepro1** [ZUGFeRD/mustangproject#294]
I use the mustang project and I would like not to have the ZUV.log file generated in my project globaly the exlusion of the logback.xml in the mustang library

**Comment by jstaerk** [comment]
currently not possible, see #259 . We can have a look together if you like.

**Comment by kassepro1** [comment]
i fix by rename the of my local logback file by rename it by logback-test.xml your can test it in the librairy

**Comment by wq9578** [comment]
I also suggest an option for disabling the creation of a log file.
In any case, creating a new directory should be avoided. A log file should be placed either in the present working directory or in the directory of the file to be validated. Maybe one should orientate at how LaTeX is dealing with log files.

**Comment by jstaerk** [comment]
I also suggest this option. I spent half a day on the failed attempt to do so, in case anybody is willing to contribute please let me know

**Comment by Heavenfighter** [comment]
The option which came with #260 -Ddisable-file-logging=true still creates log dir and empty logfile. This should not happen, since its possible that the user has no rights to write in the directory where the mustang-cli is located.
In the logback.xml the FILE appender should be surrounded by the same condition like the FILE appender-ref element, so no director and file would be created.

`
if condition='!isDefined("disable-file-logging")'>
		<appender name="FILE" ...
....
	        </appender>
</if>
`

**Comment by jstaerk** [comment]
in the library logback I now used the same like in the cli logback [7f8024c], does this help, do I need to change sth else or was this solved already anyway?

**Comment by jstaerk** [comment]
fixed with 2.8.0 : --disable-file-logging
