### ISSUE TITLE
xRechnung Unterstützung 3.0.1 ab 01.02.2024

### ISSUE THREAD

**Issue by sebastianschmitz1510** [ZUGFeRD/mustangproject#343]
Ab dem 01.02.2024 dürfen xRechnungen nur noch in der spezifizierten Version 3.0.1 angenommen werden. (https://www.e-rechnung-bund.de/standard-xrechnung-3-0-1/)
Wird diese Version bereits durch Mustangproject unterstützt oder erfolgt noch eine Implementierung?

**Comment by jstaerk** [comment]
mit entsprechenden pull requests der community gerne

**Comment by jstaerk** [comment]
at least we can validate that now. Theoretically. #316 is a pita. There used to be a sentence on the xrechnung page somewhere as for how long they would be excepting old versions, if anyone finds that we could come up with a strategy. The issue is that there are also a lot of complaints for rejects if we support prematurely. 

+of course someone one need to have a look into the neccessary changes. 

Of course 
https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.01a-INVOICE_uncefact.xml
validates, I believe the BusinessProcessSpecifiedDocumentContextParameter are new comparing to e.g. https://github.com/itplr-kosit/xrechnung-testsuite/blob/08fd1789b9d9a46340657a5a365d810389a19bb6/src/test/business-cases/standard/01.01a-INVOICE_uncefact.xml
