### ISSUE TITLE
ZUGFeRD Validator fails with ZUGFeRD 2.3 and embbeded XRechnung

### ISSUE THREAD

**Issue by hendriksander** [ZUGFeRD/mustangproject#513]
Hi, 

we use the ZUGFeRD mustangproject to validate incoming ZUGFeRD invoices. We have encountered some issues with the ZUGFeRD 2.3 version in combination with embbeded XRechnung. For functional testing of our implementation we used the ZUGFeRD XRechnung files provided by the FeRD. We tested it with the version from the FeRD website ([www.ferd-net.de/ZUGFeRD-Download](https://328833.seu2.cleverreach.com/c/99315117/80c7a9bcbb2a-skgt90)) and also with the corrected version [www.awv-net.de/upload/ferd/ZF23_DE.zip](https://328833.seu2.cleverreach.com/c/99364037/80c7a9bcbb2a-skgt90) which was later provided by a Newsletter after the initial release of ZUGFeRD 2.3. 

In the corrected version this ZUGFeRD with embedded XRechnung was provided. [XRECHNUNG_Einfach.pdf](https://github.com/user-attachments/files/17339041/XRECHNUNG_Einfach.pdf) 

The ZUGFeRD validation report results of this file are the following:
[zugferd-validierungsreport (33).txt](https://github.com/user-attachments/files/17339281/zugferd-validierungsreport.33.txt)

So it seems that the files provided by FeRD could not be validated correctly by the mustangproject or are corrupted. Can you confirm this?

Because it might be good to know we use the following code to get the ZUGFeRD profile and ZUGFeRD [core-2.14.1](https://github.com/ZUGFeRD/mustangproject/tree/core-2.14.1):

`public String getZUGFeRDProfil() {
    String guideline = this.extractString("//*[local-name() = 'GuidelineSpecifiedDocumentContextParameter']//*[local-name() = 'ID']");
    if (guideline.contains("xrechnung")) {
      return "XRECHNUNG";
    } else {
      switch (guideline) {
        case "urn:cen.eu:en16931:2017":
        case "urn:ferd:CrossIndustryDocument:invoice:1p0:comfort":
          return "COMFORT";
        case "urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic":
        case "urn:ferd:CrossIndustryDocument:invoice:1p0:basic":
          return "BASIC";
        case "urn:factur-x.eu:1p0:basicwl":
          return "BASIC WL";
        case "urn:factur-x.eu:1p0:minimum":
          return "MINIMUM";
        case "urn:ferd:CrossIndustryDocument:invoice:1p0:extended":
        case "urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended":
          return "EXTENDED";
        default:
          return "";
      }
    }
  }
`

Thanks for your help in advance.

**Comment by stgViadee** [comment]
Issue stems from the version-entry in FeRDs reference files. In profile XRECHNUNG the field value of "Version" is "3.0" which mustang validates to false: https://github.com/ZUGFeRD/mustangproject/blob/2a00af8768d60f5c18d05b17b56169045f8f7086/validator/src/main/java/org/mustangproject/validator/PDFValidator.java#L242

We face the same issue at the moment. FeRDs document "1. FACTUR-X 1.0.07 DE.pdf" states that 2p1 should be the valid version code for profile XRECHNUNG (chapter 7.7) but the reference data tells a different story. It seems as though the XRechnung version is embedded instead of the ZUGFeRD Versions: "1.2", "2.0", "2.1". Since 3.0 of XRechnung is released "3.0" should be a valid value as well. 

Is there an official version code list somewhere? Can anybody produce official documentation on the versioning of ZUGFeRD/Factur-X?

**Comment by stmue** [comment]
The official XRechnung specification can be viewed at https://xeinkauf.de/xrechnung/versionen-und-bundles/. Since XRechnung 3.0.0 the version number is 3.0. 

The information can be found on page II in the document Specification Standard XRechnung.

Kennung CIUS XRechnung:
`urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0`
Kennung Extension XRechnung:
`urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0`

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
