### ISSUE TITLE
can not create ZUGFeRD file version 2 with embedded file named "factur-x"

### ISSUE THREAD

**Issue by SabineMa** [ZUGFeRD/mustangproject#585]
My goal is to create a  ZUGFeRD file with version 2 and a file called factur-x.

I use the CLI. 

Mustang-CLI-2.14.2.jar and
Mustang-CLI-2.15.0.jar 

I have tried all combinations:

```
-format zf
-version 2 -profile M --action combine -> zugferd-invoice.xml
-version 2 -profile W --action combine -> zugferd-invoice.xml
-version 2 -profile B --action combine -> zugferd-invoice.xml
-version 2 -profile C --action combine -> error Profile not found
-version 2 -profile E --action combine -> zugferd-invoice.xml
-version 2 -profile X --action combine -> xrechnung.xml (this is ok)
-version 2 -profile T --action combine-> zugferd-invoice.xml
-version 1 -profile B --action combine -> zugferd-invoice.xml
-version 1 -profile C --action combine -> zugferd-invoice.xml
-version 1 -profile T --action combine -> zugferd-invoice.xml
```

only with `-format fx and -version 1` I get a file where the embedded file is called factur-x.

Does this mean that I have to use version 1? That seems wrong to me.
In the attached file (ZUGFeRD sample file) it says under “Invoice standard” 

“Factur-x 1.0 or ZUGFeRD 2.x profile EN16931”

so at least the call of 

`-version 2 -profile E --action combine -> zugferd-invoice.xml`

should result in such a profile, right?

Mustang-CLI-2.15.0.jar

[EN16931_Einfach.pdf](https://github.com/user-attachments/files/17917721/EN16931_Einfach.pdf)

I am new in this topic but I assume this is a bug? I suspect that this is one but I can't imagine that anyone else is complaining about it.

**Comment by yeezy69** [comment]
I have also been working with ZUGFeRD for some time. It is a bit difficult to understand due to the different ZUGFeRD versions. I hope I understood it correctly: Since version 2.1, ZUGFeRD has been adapted to the French Factur-X. The ZUGFeRD XML file is now embedded as Factur-X format:

**ZUGFeRD 2.0 only:**
URI = urn:zugferd:pdfa:CrossIndustryDocument:invoice:2p0#
zf:DocumentFileName = zugferd-invoice.xml

**ZUGFeRD 2.1 and above:**
URI = urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#
fx:DocumentFileName = factur-x.xml

Information source: Paragraph "6.3 Das PDF/A Erweiterungsschema" on page 30 in file "1. FACTUR-X 1.07.2 DE.pdf" in "ZF232_DE.zip" from ferd-net.de.


This means that for the obsolete ZUGFeRD standard 2.0 the Mustang arguments are

`--action combine --format zf --version 2 --profile E`

And for ZUGFeRD 2.1 - 2.3 the Mustang arguments are

`--action combine --format fx --version 1 --profile E`

**Comment by SabineMa** [comment]
Hi @yeezy69 thank you for your reaction. I use 
`--action combine --format fx --version 1 --profile E`
to get the desired filename. 
 I thought that `version 1` was wrong but you confirm that it seems to be not.
